version: "3.3"
services:
  database:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=appointments
      - POSTGRES_PASSWORD=appointment1234!
volumes:
  db_data:
